version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes: 
         - ~/docker-storage/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: salam-apic
      MYSQL_ROOT_HOST: '%'
    ports:
      - 6603:3306
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE <mbind operation warning>

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8183:80
