version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php:buster
 
    working_directory: ~/repo
 
    steps:
      - checkout
      - run: 
          name: Deploy Master Branch
          no_output_timeout: 30m
          command: |
            sudo apt-get update
            sudo apt-get -qq install lftp apt-utils git-ftp

            # Update Environment
            rm -rf .env
            echo "\n\n" >> .env
            echo "CI_ENVIRONMENT = production" >> .env
            echo "app.baseURL = '${CI_BASEURL}'" >> .env
            echo "database.default.hostname = localhost" >> .env
            echo "database.default.database = ${CI_DB_NAME}" >> .env
            echo "database.default.username = ${CI_DB_USER}" >> .env
            echo "database.default.password = ${CI_DB_PASS}" >> .env
            echo "database.default.DBDRIVER = MySQLi" >> .env

            # Build the application
            # composer update --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader
            composer install --prefer-dist --verbose --no-progress --dev --optimize-autoloader
            # composer install

            # Deploy the application
            echo "Deploying project ..."
            #lftp -e "set ftp:list-options -a; set ssl:verify-certificate no; open $FTP_LOCATION; user $FTP_USER $FTP_PWD; mirror -X .* -X .*/ --reverse --verbose --only-newer --delete --parallel=4 . .; bye"

            git config user.name "builder of circleci"
            git config user.email "boc@circleci.com"
            git config git-ftp.user "${FTP_USER}"
            git config git-ftp.password "${FTP_PASS}"
            git config git-ftp.url "${FTP_LOCATION}"
            git config git-ftp.syncroot ./

            # mv .gitignore gitignore
            # sed -i '/vendor/d' .gitignore
            echo "!vendor/*" > .git-ftp-include

            # echo $(git status)
            # ls -alF
            git add --all && git commit -m 'build by circleci'
            
            #echo $(git rev-parse HEAD)
            git rev-parse HEAD^ | xargs git ftp push --commit
            # git ftp push -v --changed-only --all
            git ftp push -v 
            git ftp catchup
            

            # echo $(git status)
            # git ftp catchup --init-if-not-exist --user "${FTP_USER}" --passwd "${FTP_PWD}" ${FTP_LOCATION}
 
workflows:
  version: 2
  just-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
