version: 2
jobs:
  deploy:
    docker:
      - image: circleci/7.2.0-cli
 
    working_directory: ~/repo
 
    steps:
      - checkout
 
      - run: 
          name: Deploy Master Branch
          command: |
            sudo apt-get update
            sudo apt-get -qq install apt-utils git-ftp
            echo "Deploying project ..."
            echo $(git status)
            git ftp catchup --init-if-not-exist --user "${FTP_USER}" --passwd "${FTP_PWD}" ${FTP_LOCATION}
 
workflows:
  version: 2
  just-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
